# Generated by Django 5.2 on 2025-05-06 16:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAIApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin_user',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('assistant_name', models.CharField(max_length=100)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('success_evaluation', models.TextField()),
                ('summary', models.TextField()),
                ('transcript', models.TextField()),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
