# Generated by Django 5.2 on 2025-05-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAIApp', '0002_customuser_is_admin_user_callrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='call_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
