# Generated by Django 5.2 on 2025-05-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAIApp', '0003_callrecord_call_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='call_id',
            field=models.CharField(max_length=255),
        ),
    ]
