# Generated by Django 5.2 on 2025-05-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAIApp', '0004_alter_callrecord_call_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='call_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
