# Generated by Django 5.2 on 2025-05-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAIApp', '0005_alter_callrecord_call_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='monthly_seconds_used',
            field=models.IntegerField(default=0),
        ),
    ]
