# Generated by Django 5.2 on 2025-05-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAIApp', '0007_dealership_customuser_dealership'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='success_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
