# Generated by Django 5.2 on 2025-06-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAIApp', '0008_callrecord_success_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='outcome',
            field=models.CharField(default='fail', max_length=10),
        ),
    ]
