# Generated by Django 5.2 on 2025-06-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAIApp', '0009_callrecord_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='outcome',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10, null=True),
        ),
    ]
