# Generated by Django 5.2.4 on 2025-10-03 00:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAIApp', '0010_alter_callrecord_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=255, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('outcome', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10, null=True)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('success_score', models.IntegerField(blank=True, null=True)),
                ('acknowledging_score', models.IntegerField(blank=True, null=True)),
                ('acknowledging_reason', models.TextField(blank=True, null=True)),
                ('acknowledging_suggestion', models.TextField(blank=True, null=True)),
                ('reframing_score', models.IntegerField(blank=True, null=True)),
                ('reframing_reason', models.TextField(blank=True, null=True)),
                ('reframing_suggestion', models.TextField(blank=True, null=True)),
                ('handling_score', models.IntegerField(blank=True, null=True)),
                ('handling_reason', models.TextField(blank=True, null=True)),
                ('handling_suggestion', models.TextField(blank=True, null=True)),
                ('securing_score', models.IntegerField(blank=True, null=True)),
                ('securing_reason', models.TextField(blank=True, null=True)),
                ('securing_suggestion', models.TextField(blank=True, null=True)),
                ('respect_score', models.IntegerField(blank=True, null=True)),
                ('respect_reason', models.TextField(blank=True, null=True)),
                ('respect_suggestion', models.TextField(blank=True, null=True)),
                ('final_comments', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
