# Generated by Django 5.2.4 on 2026-03-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAIApp', '0012_callanalysis_assistant_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='callanalysis',
            index=models.Index(fields=['user', 'assistant_name'], name='AAIApp_call_user_id_fa2eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='callanalysis',
            index=models.Index(fields=['user', 'call_id'], name='AAIApp_call_user_id_646002_idx'),
        ),
        migrations.AddIndex(
            model_name='callanalysis',
            index=models.Index(fields=['user', 'timestamp'], name='AAIApp_call_user_id_4044b4_idx'),
        ),
    ]
